### ISSUE TITLE
Units moving diagonally are faster than units moving straight up or down

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsGamePatch#123]
Units moving diagonally are faster than units moving straight up or down. Potentially up to 1.41x faster (sqrt(2)). Investigate.

**Comment by Jundiyy** [comment]
Not sure if this is worth the fix? Would change gameplay quite a bit.

**Comment by xezon** [comment]
No it would not change gameplay. The proper fix would be to correct the math and then scale the speed by a constant between the previous min and max speed.

This fix can not be done in INI, only in game code. I don't know where to look for this calculation.

**Comment by Jundiyy** [comment]
Oh right, so in game it's the same but in code would be different.

**Comment by xezon** [comment]
Well units would always move at same speed then, no matter if vertical, horizontal or diagonal. I am not aware about gameplay benefits of having units move at different speeds depending on their direction. It is a bug, but we likely will not be able to fix it.

**Comment by Jundiyy** [comment]
👍

**Comment by RisingZH** [comment]
This would change the gameplay and make the game feel completely different , so I wouldn't recommend it. Currently you are better off retreating diagonally in certain situations.

Guessing the game works like this as the map is split into tiles and units are made to travel a certain number of tiles a second, regardless of direction.

**Comment by Madrageeeeee** [comment]
Kindnif agree with rising here. Would make the game feel quite different. 

Would not change
